### ISSUE TITLE
无法运行，提示出错，缺少文件

### ISSUE THREAD

**Issue by oldzhg** [TimWei/haijin_kabe#11]
```
$ ruby init.rb
Initializing...
Downloading images
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mechanize (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/oldzhg/develop/haijin_kabe/lib/download.rb:4:in `<top (required)>'
	from init.rb:3:in `require_relative'
	from init.rb:3:in `<main>'

```

系统环境：MacBook Air ， OS X10.13.2

**Comment by TimWei** [comment]
@oldzhg 

缺少依赖

你有先执行 bundle install安装依赖么？

如果有执行过仍跑出这错误

检查下你的网路环境能否正常解析 rubygems.org

不能正常解析rubygems.org的话，把Gemfile内的source换成国内对应的rubygems镜像站即可
